name: Git acción con JavaScript

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        run: |
          curl -X POST -d "Se ha ejecutado un archivo: 'Hola Mundo - Maria Mercedes Rosario 2023-1897'" https://ntfy.sh/devops-itla
